version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps3-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: deps3-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
      - run:
          name: build
          command: npm run build
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
